package utils

const (
	ENV_NAME_APP_PORT           = "APP_PORT"
	ENV_NAME_POSTGRES_HOST      = "DATABASE_POSTGRES_HOST"
	ENV_NAME_POSTGRES_USER      = "DATABASE_POSTGRES_USER"
	ENV_NAME_POSTGRES_PASSWORD  = "DATABASE_POSTGRES_PASSWORD"
	ENV_NAME_POSTGRES_DATABASE  = "DATABASE_POSTGRES_DATABASE"
	ENV_NAME_POSTGRES_PORT      = "DATABASE_POSTGRES_PORT"
	ENV_NAME_NEW_RELIC_APP_NAME = "NEW_RELIC_APP_NAME"
	ENV_NAME_NEW_RELIC_TOKEN    = "NEW_RELIC_TOKEN"
	ENV_NAME_NEW_RELIC_ENABLED  = "NEW_RELIC_ENABLED"
	ENV_NAME_URI_GITHUB_API     = "URI_GITHUB_API"
)
